
HRNetArchConfig:
  _target_: mseg_semantic.model.seg_hrnet_config.HRNetArchConfig
  FINAL_CONV_KERNEL: 1
  
  STAGE1:
    _target_: mseg_semantic.model.seg_hrnet_config.HRNetStageConfig
    NUM_MODULES: 1
    NUM_BRANCHES: 1
    BLOCK: BOTTLENECK
    NUM_BLOCKS: [4]
    NUM_CHANNELS: [64]
    FUSE_METHOD: SUM
  
  STAGE2:
    _target_: mseg_semantic.model.seg_hrnet_config.HRNetStageConfig
    NUM_MODULES: 1
    NUM_BRANCHES: 2
    BLOCK: BASIC
    NUM_BLOCKS: [4, 4]
    NUM_CHANNELS: [48, 96]
    FUSE_METHOD: SUM

  STAGE3:
    _target_: mseg_semantic.model.seg_hrnet_config.HRNetStageConfig
    NUM_MODULES: 4
    NUM_BRANCHES: 3
    BLOCK: BASIC
    NUM_BLOCKS: [4, 4, 4]
    NUM_CHANNELS: [48, 96, 192]
    FUSE_METHOD: SUM

  STAGE4:
    NUM_MODULES: 3
    NUM_BRANCHES: 4
    BLOCK: BASIC
    NUM_BLOCKS: [4, 4, 4, 4]
    NUM_CHANNELS: [48, 96, 192, 384]
    FUSE_METHOD: SUM
